add client wrapper
crypto-org-chain/chain-jslib pull request #186
Opened 2021-04-19 09:46 UTC by thomas-nguy

*Create a client wrapper over 'StargateClient' and 'QueryClient' from cosmosjs

Before users need to manually import cosmosjs client into their project and configure them to be compatible with our chain.
This can be the source of errors and it requires extra effort to use the SDK
- Need to find a cosmosjs version which is compatible with crypto.com chain version
- Make sure to uses the methods supported (ie use broadcast instead of StargateSigningClient to send tx)
- QueryClient needs to be initialise with the module supported manually 

The wrapper encapsulate the transactions client and query client into an object and expose the functions only supported.
No need also to import extra packages.

2021-04-19 10:07 UTC, thomas-nguy commented on lib/src/client/client.ts
> +            this.queryClient = QueryClient.withExtensions(
they are the only supported module for now.
I did not add IBCExtension since its not active yet

2021-04-20 05:00 UTC, cdc-Hitesh submitted a review, later dismissed

2021-04-20 09:13 UTC, calvinaco requested changes
Overall looks good to me. Left a small comment on the README. 

I notice you have committed the `yarn.lock, but in this porject we use `npm` so it is better to remove it and perhaps add it to `.gitgnore` list.

Thanks!

2021-04-20 12:30 UTC, thomas-nguy commented on README.md
> +The SDK uses cosmosjs stargate client to send transactions. For more information, check
thanks, fixed

2021-04-20 12:30 UTC, thomas-nguy commented on README.md
> +The SDK uses cosmosjs queryclient to query the blockchain. For more information, check
thanks, fixed

2021-04-21 04:36 UTC, calvinaco approved these changes

2021-04-21 05:02 UTC, merged