Problem: Feature transaction decoding support
crypto-org-chain/chain-jslib pull request #189
Opened 2021-04-22 22:28 UTC by cdc-Hitesh

Fixes #165 

Todo: 
- More unit test case
- To check for unsigned transactions

2021-04-23 09:19 UTC, thomas-nguy commented
I would squash those commits messages for more readibility but overall lgtm

2021-04-23 09:21 UTC, thomas-nguy submitted a review, later dismissed

2021-04-23 14:49 UTC, cdc-Hitesh commented
> I would squash those commits messages for more readibility but overall lgtm

Thanks for the mention. Let me try it next time. 
@thomas-nguy

2021-05-02 08:26 UTC, calvinaco reviewed
Excellent work! This is a long-wanted feature. I have left some comment for clarification. Thanks!

2021-05-02 12:18 UTC, cdc-Hitesh commented on lib/src/client/client.spec.ts
> +                const croHttpClient = await cro.CroClient.connect(CroNetwork.Testnet.rpcUrl);
Well agreed and noted.
This might become a problem ahead.

2021-05-02 12:18 UTC, cdc-Hitesh commented on lib/src/transaction/msg/gov/MsgVote.spec.ts
> +            option: VoteOption.VOTE_OPTION_NO_WITH_VETO,
I had to increase the unit test line coverage to pass codecov CI pipeline 😢

2021-05-02 12:19 UTC, cdc-Hitesh commented on lib/src/transaction/msg/gov/MsgVote.spec.ts
> +            option: VoteOption.VOTE_OPTION_ABSTAIN,
Same as to increease unit test coverage To pass CI

2021-05-02 12:19 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +     */
Noted.

2021-05-02 12:19 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +     * @returns TxDecode
Noted.

2021-05-02 13:59 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +            signatures = signaturesArray.map((e) => toBase64(e !== undefined ? e : new Uint8Array()));
>does it means that in the signatureArray, it is possible to have element which is just undefined?
Basically an empty array of Signatures in case of an `undefined` element.

>On the other hand, it is recommended to use typeof e !== 'undefined'
Hmm. This is interesting.

>In addition, can you add a test cases to cover this case. This will be a good scenario to cover.


Sure.

2021-05-02 14:03 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +            obj.signerInfos = authInfo.signerInfos.map((e) => (e ? this.getSignerInfoJson(e) : undefined));
I get it. Sounds good.
I am wondering how to create an encoded hex for the case above. Anyways, THanks.

2021-05-02 14:04 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +        const stringifiedSignerInfo = JSON.stringify(SignerInfo.toJSON(signerInfo) as string);
`.toJSON` returns an `unknown` type, and my ts-compiler was throwing a syntax error, but it was resolved once I used `as string`

2021-05-02 14:05 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +    // transforms `type_url` to `@type` to match GoLang's TxDecoder JSON output
Okay sure thing.

2021-05-03 04:44 UTC, calvinaco commented on lib/src/transaction/msg/gov/MsgVote.spec.ts
> +            option: VoteOption.VOTE_OPTION_NO_WITH_VETO,
lolll, can't we just add a few more test cases to cover different options?

2021-05-03 04:47 UTC, calvinaco commented on lib/src/utils/txDecoder.ts
> +            signatures = signaturesArray.map((e) => toBase64(e !== undefined ? e : new Uint8Array()));
> Basically an empty array of Signatures in case of an undefined element.

Sorry I don't quite understand. If the Signatures array is empty, `.map` should not iterate any element?

2021-05-03 04:47 UTC, calvinaco commented on lib/src/utils/txDecoder.ts
> +            obj.signerInfos = authInfo.signerInfos.map((e) => (e ? this.getSignerInfoJson(e) : undefined));
Yes, I wonder if such a case exists. That's why I raise here

2021-05-03 04:48 UTC, calvinaco commented on lib/src/utils/txDecoder.ts
> +        const stringifiedSignerInfo = JSON.stringify(SignerInfo.toJSON(signerInfo) as string);
But `SignerInfo.toJSON(signerInfo)` should return an object but not string? Perhaps do
```suggestion
        const stringifiedSignerInfo = JSON.stringify(SignerInfo.toJSON(signerInfo) as any);
```

2021-05-03 11:04 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +            signatures = signaturesArray.map((e) => toBase64(e !== undefined ? e : new Uint8Array()));
>Sorry I don't quite understand. If the Signatures array is empty, .map should not iterate any element?

Yes exactly.

2021-05-03 12:15 UTC, calvinaco commented on lib/src/utils/txDecoder.ts
> +            signatures = signaturesArray.map((e) => toBase64(e !== undefined ? e : new Uint8Array()));
Then what's the need of checking `e !== undefined`?

2021-05-03 17:30 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +            signatures = signaturesArray.map((e) => toBase64(e !== undefined ? e : new Uint8Array()));
We are processing this input after decoding from third party libs and also this piece of code is inspired by their library. Hence I kept it.

2021-05-05 02:18 UTC, calvinaco commented on package.json
> +    "@types/nock": "^11.1.0",
```suggestion
    "@types/nock": "^11.1.0",
```

This should be a dev dependecies?

2021-05-05 02:18 UTC, calvinaco requested changes
One more comment on the dependencies and we are good to merge

2021-05-05 05:39 UTC, cdc-Hitesh commented on package.json
> +    "@types/nock": "^11.1.0",
This is true.  Fixed.

Thanks

2021-05-05 11:19 UTC, calvinaco approved these changes

2021-05-05 11:19 UTC, merged