add new testnet config
crypto-org-chain/chain-jslib pull request #234
Opened 2021-05-26 02:11 UTC by thomas-nguy

2021-05-26 02:57 UTC, calvinaco requested changes
Testnet2 maybe a bit confusing, other configs look good to me.

2021-05-26 02:57 UTC, calvinaco commented on lib/src/core/cro.ts
> +    public static Testnet2: Network = {
```suggestion
    public static TestnetCroeseid3: Network = {
```

2021-05-26 04:03 UTC, mannutech approved these changes

2021-05-27 01:42 UTC, thomas-nguy commented on lib/src/core/cro.ts
> +    public static Testnet2: Network = {
fixed

2021-05-28 10:02 UTC, merged