Problem: Initial changes for new offline signing approach
crypto-org-chain/chain-jslib pull request #241
Opened 2021-06-02 08:52 UTC by cdc-Hitesh

Fixes #26 
Fixes #240

2021-06-04 09:49 UTC, calvinaco reviewed
Great work @cdc-Hitesh , the documentation is really helpful.

 I have reviewed half of it and I think I should submit what I have reviewed so far first while I continue.

2021-06-04 09:49 UTC, calvinaco commented on README.md
> +const exportSignerInfoToJSON = rawTx.exportSignerAccounts() as string;
```suggestion
const exportUnsignedCosmosJSON = rawTx.toCosmosJSON();
const exportSignerInfoToJSON = rawTx.exportSignerAccounts();
```

2021-06-04 09:49 UTC, calvinaco commented on lib/src/coin/coin.ts
>           * @param {string} amount coins amount represented as string
```suggestion
         * @param {string} amount coin amount represented as string
```

2021-06-04 09:49 UTC, calvinaco commented on lib/src/coin/coin.ts
>           * @param {Units} unit unit of the coins
Missing denom params here

2021-06-04 09:49 UTC, calvinaco commented on lib/src/coin/coin.ts
>              this.baseAmount = unit === Units.BASE ? Coin.parseBaseAmount(coins) : Coin.parseCROAmount(coins);
By reading the code, the logic here assumes if the base amount is not in base unit, it will be CRO. Is this a restriction we deliberately add? If yes, should we further check if is  one of the supported denoms? (i.e. CRO, TCRO)?

Otherwise in `parseCROAmount` there will be some currency conversion and total supply check which may not be expected by users.

2021-06-04 09:49 UTC, calvinaco commented on lib/src/cosmos/v1beta1/types/cosmostx.ts
> +export interface CosmosTx {
We should add a lint ignore rules here.

2021-06-04 09:49 UTC, calvinaco commented on lib/src/cosmos/v1beta1/types/ow.types.ts
> +    owOptionalStrictObject().exactShape({
If we change it to be optional, please also update the variable name to `owOptionalTxBody` for readability. Thanks Hitesh.

2021-06-04 09:49 UTC, calvinaco commented on lib/src/transaction/msg/bank/msgsend.spec.ts
> +        });
Please add a check for the validness of address, thanks Hitesh.

2021-06-04 09:49 UTC, calvinaco commented on lib/src/transaction/msg/bank/msgsend.ts
> +                // TOdo: Handle the complete list
```suggestion
                // TODO: Handle the complete list
```

2021-06-04 09:49 UTC, calvinaco commented on lib/src/transaction/ow.types.ts
> +// import { owAuthInfo, owTxBody } from '../cosmos/v1beta1/types/ow.types';
```suggestion
```

2021-06-04 09:49 UTC, calvinaco commented on lib/src/transaction/ow.types.ts
> +    owOptionalStrictObject().exactShape({
Please rename the variable to `owOptionalSignerAccount`

2021-06-04 09:49 UTC, calvinaco commented on lib/src/transaction/ow.types.ts
> +    signerAccounts: ow.optional.array.ofType(owSignerAccount()),
Actually do we need to mark `SignerAccount` to be optional?
What we are referring here is 
1. An optional array of signer account; or
2. An optional array in which inside is an optional element of signer account?
I believe it's former?

2021-06-04 11:39 UTC, cdc-Hitesh commented on lib/src/coin/coin.ts
>              this.baseAmount = unit === Units.BASE ? Coin.parseBaseAmount(coins) : Coin.parseCROAmount(coins);
I agree.

> Is this a restriction we deliberately add?

I didn't touch it, to not break anything.

Solution: Let me write a condition to check on the `unit`.

2021-06-04 11:51 UTC, cdc-Hitesh commented on lib/src/cosmos/v1beta1/types/cosmostx.ts
> +export interface CosmosTx {
Thanks for noticing.
I have done it in future PRs bt it makes sense to have it from the beginning.

2021-06-04 11:55 UTC, cdc-Hitesh commented on lib/src/transaction/msg/bank/msgsend.spec.ts
> +        });
My understanding says
the `validateAddresses` function of msgsend.ts should be handling this?
As we are constructing an instance at the return.

The above test case would fail on the invalid address at construction.

Am I missing something?

2021-06-04 11:58 UTC, cdc-Hitesh commented on lib/src/transaction/ow.types.ts
> +    owOptionalStrictObject().exactShape({
Done. Thanks

2021-06-04 12:02 UTC, cdc-Hitesh commented on lib/src/transaction/ow.types.ts
> +    signerAccounts: ow.optional.array.ofType(owSignerAccount()),
I want to keep `signerAccounts` optional parameter. 
so that means 🤔  Option 1.

I will change the constructor params object.

2021-06-04 12:04 UTC, cdc-Hitesh commented on lib/src/transaction/ow.types.ts
> +    signerAccounts: ow.optional.array.ofType(owSignerAccount()),
Let me know if I missed something.

2021-06-05 04:20 UTC, calvinaco requested changes
Bravo! I have reviewed the updated and those I left off. Overall this PR is awesome. I left more comments but overall this is a huge progress.

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.spec.ts
> +            const parsedCosmosJson = JSON.parse(anyTx.toCosmosJSON() as string);
```suggestion
            const parsedCosmosJson = JSON.parse(anyTx.toCosmosJSON());
```

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.spec.ts
> +            expect(parseInt(parsedCosmosJson.auth_info.fee.gas_limit, 10)).to.greaterThan(0);
Hello Hitesh, a small suggestion, can we do it like this to have a more precise test of the result?

```suggestion
            const expectedJSONStr = '{ "body": { "messages": [{ "@type": "/cosmos.bank.v1beta1.MsgSend", "amount": [{ "denom": "basetcro", "amount": "3478499933290496" }], "from_address": "tcro1x07kkkepfj2hl8etlcuqhej7jj6myqrp48y4hg", "to_address": "tcro184lta2lsyu47vwyp2e8zmtca3k5yq85p6c4vp3" }], "memo": "", "timeout_height": "0", "extension_options": [], "non_critical_extension_options": [] }, "auth_info": { "signer_infos": [{ "public_key": { "@type": "/cosmos.crypto.secp256k1.PubKey", "key": "Ap/w6zWJiX6QCKLTt6jLM1sFJsUmBWaS6VUi7zxqqb0V" }, "mode_info": { "single": { "mode": "SIGN_MODE_DIRECT" } }, "sequence": "794129105682432" }], "fee": { "amount": [], "gas_limit": "8105066556817408", "payer": "", "granter": "" } }, "signatures": [""] }';
            const actualJSONStr = anyTx.toCosmosJSON();
            expect(actualJSONStr).to.deep.eq(expectedJSONStr);
            expect(() => JSON.parse(actualJSONStr)).not.to.throw();
```

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.spec.ts
> +            expect(parseInt(parsedCosmosJson.auth_info.fee.gas_limit, 10)).to.greaterThan(0);
The above code is not tested, just to illustrate my idea.

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.ts
>          }
Can you explain the intention of this section, thank you.

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +            if (!publicKeyObj.key) {
Here it hurts a bit on the readability a bit, can we do?
```suggestion
            if (!signerInfo.mode_info.single) {
```

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +            if (!publicKeyObj.key) {
because not having `publicKeyObj.key` does not imply it is a single sign if you do not have knowledge of how multisig Cosmos JSON looks like

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        if (cosmosAuthInfo.fee.amount.length === 1) {
This is check is not necessary if we check `if (cosmosAuthInfo.fee.amount.length > 1) {` above already?

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +export const protoEncodeTxBody = (txBody: TxBody): Bytes => {
Since this function is used by both `RawTransaction` and here, please consider extract it to a common file

2021-06-05 04:20 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +export const protoEncodeAuthInfo = (authInfo: AuthInfo): Bytes => {
Since this function is used by both `RawTransaction` and here, please consider extract it to a common file

2021-06-05 04:20 UTC, calvinaco commented on lib/src/utils/address.ts
> +// Todo: we can rename it to `validateAddressByNetwork`
```suggestion
// TODO: we can rename it to `validateAddressByNetwork`
```

2021-06-05 04:20 UTC, calvinaco commented on lib/src/utils/address.ts
> +        return Bytes.fromUint8Array(new Uint8Array(bech32.fromWords(words.slice(5))));
May I know what is this magic number 5? Thank you

2021-06-05 04:20 UTC, calvinaco commented on lib/src/utils/txDecoder.spec.ts
> +
```suggestion
```
Remove unneeded lines

2021-06-05 04:20 UTC, calvinaco commented on lib/src/utils/txDecoder.spec.ts
> +        }).to.throw('Missing type_url in Any');
The error message is not aligned with the test
```
it('should throw on empty messages array'
```

Is it expected?

2021-06-05 04:20 UTC, calvinaco commented on lib/src/utils/txDecoder.spec.ts
> +            timeout_height: '0',
Can you add one extra test cases with the `timeout_height` set to non-default value? Appreciate it

2021-06-05 04:20 UTC, calvinaco commented on lib/src/utils/txDecoder.ts
> +    // TODO: Make it generic when encounter new cases
Is this comment outdated?

2021-06-05 06:06 UTC, cdc-Hitesh commented on lib/src/utils/address.ts
> +        return Bytes.fromUint8Array(new Uint8Array(bech32.fromWords(words.slice(5))));
This is my bad. Hahahha. 
I was trying to achieve conversion from `cons pub key` to `Tendermint Pub key`.

Solution: I will remove this for now. It will create confusion.

2021-06-05 06:14 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +    // TODO: Make it generic when encounter new cases
No, it still holds true.
**Reason:** We are using `cosmjs` for decoding the `txBody`, hence needed this custom handling.

2021-06-05 07:14 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
>          }
Yes,
If you see the `/simulate` endpoint, It accepts JSON value with `tx` as a key on the top.
Hence, when we call `.toCosmosJSON()`  it exports with a `tx` as the top object.
Hence I had to write this custom logic.

2021-06-05 07:17 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +            if (!publicKeyObj.key) {
Makes sense.
 I have made changes.
 resolved.

2021-06-05 07:18 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +export const protoEncodeTxBody = (txBody: TxBody): Bytes => {
Noted.

2021-06-05 07:22 UTC, cdc-Hitesh commented on lib/src/utils/address.ts
> +        return Bytes.fromUint8Array(new Uint8Array(bech32.fromWords(words.slice(5))));
I have removed this change to avoid confusion.

2021-06-05 07:23 UTC, cdc-Hitesh commented on lib/src/utils/address.ts
> +        return Bytes.fromUint8Array(new Uint8Array(bech32.fromWords(words.slice(5))));
I will revisit this section when working with custom network addresses or IBC.
resolved

2021-06-09 04:44 UTC, calvinaco requested changes

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/ow.types.ts
> +import { owBig, owStrictObject, owOptionalStrictObject } from '../ow.types';
```suggestion
import { owBig, owStrictObject } from '../ow.types';
```

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.spec.ts
> +            expect(parseInt(parsedCosmosJson.auth_info.fee.gas_limit, 10)).to.greaterThan(0);
@cdc-Hitesh gentle nudge in case you miss this

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.ts
>          }
Will this make it incompatible when passed to chain-maind CLI?

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        if (cosmosAuthInfo.fee.amount.length === 1) {
@cdc-Hitesh gentle nudge

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        // TODO: structure integrity check
@cdc-Hitesh gentle nudge

It can be done in later PR, but just want to maker sure this is delivered.

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +    public toCosmosJSON(): unknown {
```suggestion
    public toCosmosJSON(): string {
```

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +export const protoEncodeTxBody = (txBody: TxBody): Bytes => {
@cdc-Hitesh gentle nudge here

2021-06-09 04:44 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +export const protoEncodeAuthInfo = (authInfo: AuthInfo): Bytes => {
@cdc-Hitesh gentle nudge here

2021-06-09 04:44 UTC, calvinaco commented on lib/src/utils/address.ts
> +        //TODO: Revisit this when working with IBC or custom network addresses
```suggestion
        // TODO: Revisit this when working with IBC or custom network addresses
```

2021-06-09 08:24 UTC, cdc-Hitesh commented
> Multiple authInfo fees

I have created a separate issue to be taken up post this.

> when `tx` is the top object, it works with CLI?

I tested, it doesn't work.

cc @calvinaco

2021-06-09 08:53 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.spec.ts
> +        }).to.throw('Missing type_url in Any');
- I have changed the error message.
- I have included this special case for edge scenario in case.

2021-06-09 08:53 UTC, cdc-Hitesh commented on lib/src/transaction/raw.ts
> +        public exportSignerAccounts(): unknown {
resolved

2021-06-09 08:54 UTC, cdc-Hitesh commented on lib/src/transaction/ow.types.ts
> +import { owBig, owStrictObject, owOptionalStrictObject } from '../ow.types';
resolved

2021-06-09 08:54 UTC, cdc-Hitesh commented on lib/src/utils/address.ts
> +        //TODO: Revisit this when working with IBC or custom network addresses
resolved

2021-06-10 05:13 UTC, calvinaco requested changes

2021-06-10 05:13 UTC, calvinaco commented on lib/src/coin/coin.ts
> +                }
@cdc-Hitesh is the test cases added?

2021-06-10 05:37 UTC, cdc-Hitesh commented on lib/src/coin/coin.ts
> +                }
@calvinaco 
For backward compatibility, I see `msgsend.spec.ts` works fine as expected without any changes.
So existing tests should vouch for the changes in `coin.ts`

What do you think?

2021-06-10 05:38 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        // TODO: structure integrity check
Sure. What would you want to see in the integrity check?
I will create a new issue.

2021-06-10 08:12 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        // TODO: structure integrity check
I think it would be to check if the AuthInfo and Body are valid. Not sure how much it is covered now?

2021-06-10 08:12 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        // TODO: structure integrity check
You can resolve this after you link the issue here. Thanks @cdc-Hitesh

2021-06-10 08:18 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        // TODO: structure integrity check
issue created: https://github.com/crypto-org-chain/chain-jslib/issues/274

2021-06-10 08:27 UTC, calvinaco commented on lib/src/coin/coin.ts
> +                }
I still think it will be good to have a dedicated test for it to increase our confidence level.

2021-06-10 08:32 UTC, calvinaco commented on lib/src/cosmos/v1beta1/types/ow.types.ts
> +    owOptionalStrictObject().exactShape({
@cdc-Hitesh gentle nudge

2021-06-10 08:34 UTC, calvinaco commented on lib/src/transaction/msg/bank/msgsend.spec.ts
> +        });
Yes, this is correct. But in the test case standpoint, our concern is that `.fromCosmosMsgJSON()` should throw when the address is invalid. So that's why this test case is still important.

2021-06-10 08:38 UTC, calvinaco commented on lib/src/transaction/signable.ts
>          }
According to later comment, this is proved to be incompatible and the tx prop is now removed from `toCosmosJSON()`

2021-06-10 08:40 UTC, calvinaco commented on lib/src/utils/txDecoder.ts
> +    // TODO: Make it generic when encounter new cases
@cdc-Hitesh let's take a deep dive into it offline.

2021-06-10 09:13 UTC, cdc-Hitesh commented on lib/src/transaction/signable.spec.ts
> +            expect(parseInt(parsedCosmosJson.auth_info.fee.gas_limit, 10)).to.greaterThan(0);
Thanks. 
Resolved.

2021-06-10 09:13 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        if (cosmosAuthInfo.fee.amount.length === 1) {
the variable `cosmosAuthInfo.fee.amount.length` can be ZERO(0) also, hence I have kept this length check again.

2021-06-10 09:17 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        if (cosmosAuthInfo.fee.amount.length === 1) {
But on line 153 you already checked is it greater than 1?
```
if (cosmosAuthInfo.fee.amount.length > 1) {
            // TODO: Multi-coin support
            throw new Error(`More than one fee amount in transaction is not supported`);
        }
```

2021-06-10 16:35 UTC, calvinaco approved these changes

2021-06-10 18:15 UTC, merged