Problem: Missing chainmaind CLI level NFT types params validation and amino JSON support
crypto-org-chain/chain-jslib pull request #260
Opened 2021-06-06 05:00 UTC by calvinaco

Fix #224
Fix #259

2021-06-06 05:33 UTC, eddycpc approved these changes

2021-06-07 06:12 UTC, cdc-Hitesh commented
@calvinaco 
This is a precise piece of work. Awesome.
I have a small comment on the validation part:
- I see there is a URI length check on Golang CLI ([link](https://github.com/crypto-org-chain/chain-main/blob/88d06257ecd3a7a5c5cdf6dee0d4135b2661a6c9/x/nft/types/validation.go#L59))
- Also name cannot have a `space` in it (link)[https://github.com/crypto-org-chain/chain-main/blob/88d06257ecd3a7a5c5cdf6dee0d4135b2661a6c9/x/nft/types/validation.go#L39]

Do we wish to incorporate these changes as well? or we can go ahead without this too?

2021-06-07 07:39 UTC, cdc-Hitesh requested changes
The message type value needs to change.
I will create a separate PR as @calvinaco is on holiday today.

2021-06-07 07:39 UTC, cdc-Hitesh commented on lib/src/cosmos/amino/msg.ts
> +    return (msg as MsgMintNFT).type === 'cosmos-sdk/MsgMintNFT';
After testing I discovered the type will be `chainmain/nft/MsgMintNFT`

It doesn't accept `'cosmos-sdk/MsgMintNFT`

The same holds true for all NFT messages.

2021-06-07 07:39 UTC, cdc-Hitesh commented on lib/src/cosmos/amino/msg.ts
> +    return (msg as MsgEditNFT).type === 'cosmos-sdk/MsgEditNFT';
Same as above, will need to change the `type` here

2021-06-07 07:39 UTC, cdc-Hitesh commented on lib/src/cosmos/amino/msg.ts
> +    return (msg as MsgBurnNFT).type === 'cosmos-sdk/MsgBurnNFT';
Same as above, will need to change the `type` here

2021-06-07 07:39 UTC, cdc-Hitesh commented on lib/src/cosmos/amino/msg.ts
> +    return (msg as MsgTransferNFT).type === 'cosmos-sdk/MsgTransferNFT';
Same as above will need to change the `type` here.
For brevity I am skipping details

2021-06-07 08:40 UTC, cdc-Hitesh commented
Marking above PR for NFM.

2021-06-08 04:45 UTC, calvinaco commented
Close this in favour of #268

2021-06-08 04:45 UTC, closed without merging