[Ready -4] Problem: Support Multiple AuthInfo Fee Amount
crypto-org-chain/chain-jslib pull request #277
Opened 2021-06-14 09:06 UTC by cdc-Hitesh

Fixes #272

2021-06-18 10:07 UTC, calvinaco requested changes
The code looks good to me, but since this change affect tx construction, please add unit test and e2e tests for multiple coin cases. Thank you

2021-06-18 10:09 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        });
Consider using `.map`

2021-06-21 07:06 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        });
sure thanks

2021-06-21 07:13 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        });
Btw, Can I understand the benefit of using `.map` here? Or is it more of a general practice?

2021-06-21 15:08 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        });
@calvinaco

2021-06-23 07:28 UTC, calvinaco commented on lib/src/transaction/signable.ts
> +        });
`.forEach` is more for iterating elements, but in this example you are iterating it and then return a new array based on the values, which makes it a perfect use of `.map`.

At the end of the day both will works, but it is more intuitive to use `.map` in thsi case.

2021-06-23 10:43 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        });
I see. Got it. Using .map will even save me a line or two.

2021-06-23 10:46 UTC, cdc-Hitesh commented on lib/src/transaction/signable.ts
> +        });
Resolved.

2021-06-23 10:57 UTC, calvinaco commented on lib/src/transaction/raw.ts
> +         * @deprecated
Is this supposed to be deprecated?

2021-06-23 10:57 UTC, calvinaco approved these changes

2021-06-23 11:00 UTC, cdc-Hitesh commented on lib/src/transaction/raw.ts
> +         * @deprecated
Good catch, 
Only `setFee` is supposed to be deprecated.

2021-06-23 11:08 UTC, merged