Problem: Offline Signing Support & TxDecoder
crypto-org-chain/chain-jslib pull request #298
Opened 2021-07-13 08:56 UTC by cdc-Hitesh

2021-07-13 09:10 UTC, eddycpc commented on lib/src/coin/coin.spec.ts
> +            // });
Unused code can be cleaned up

2021-07-13 09:11 UTC, eddycpc requested changes

2021-07-13 09:11 UTC, eddycpc commented on lib/src/coin/coin.spec.ts
> +    xdescribe('add', function () {
```suggestion
    describe('add', function () {
```

Please re-enable again these tests

2021-07-13 09:48 UTC, eddycpc commented on lib/src/coin/coin.ts
> +        public readonly denom: string;
If this value is optional can we also specify that it's optional in the type system so that it doesn't cause unwanted effects? 🤔

2021-07-13 10:32 UTC, eddycpc commented on lib/src/coin/coin.ts
> -            this.baseAmount = unit === Units.BASE ? Coin.parseBaseAmount(coins) : Coin.parseCROAmount(coins);
Quick question: Is this change backwards compatible?

2021-07-13 11:06 UTC, cdc-Hitesh commented on lib/src/coin/coin.spec.ts
> +    xdescribe('add', function () {
I have a challenge here.
This specific test case is failing when I enable it.
I tried spending some time with this one earlier but didn't work.

2021-07-13 11:07 UTC, cdc-Hitesh commented on lib/src/coin/coin.ts
> -            this.baseAmount = unit === Units.BASE ? Coin.parseBaseAmount(coins) : Coin.parseCROAmount(coins);
Yes, this is. 
I have spent some time with this one and added a few extra test cases too for this.

2021-07-13 11:14 UTC, cdc-Hitesh commented on lib/src/coin/coin.spec.ts
> +            // });
noted.

2021-07-13 14:06 UTC, eddycpc commented on lib/src/cosmos/v1beta1/types/tx.ts
> +        amount?: ICoin[];
I'm curious to learn how this is made and keeps backward compatibility at the same time. Since the core type is being changed here

2021-07-13 14:07 UTC, eddycpc commented on lib/src/transaction/msg/distribution/MsgFundCommunityPool.spec.ts
> +            '0a760a740a312f636f736d6f732e646973747269627574696f6e2e763162657461312e4d736746756e64436f6d6d756e697479506f6f6c123f0a100a08626173657463726f120431303030122b7463726f313635747a63726832796c38
Signature change?

2021-07-13 18:05 UTC, cdc-Hitesh commented on lib/src/cosmos/v1beta1/types/tx.ts
> +        amount?: ICoin[];
For different message types, I have added a `v2` version in the `core.ts`
But this change has been specifically done to support multiple denom.

2021-07-13 18:11 UTC, cdc-Hitesh commented on lib/src/transaction/msg/distribution/MsgFundCommunityPool.spec.ts
> +            '0a760a740a312f636f736d6f732e646973747269627574696f6e2e763162657461312e4d736746756e64436f6d6d756e697479506f6f6c123f0a100a08626173657463726f120431303030122b7463726f313635747a63726832796c38
Yes good  catch,
Because of this line https://github.com/crypto-org-chain/chain-jslib/pull/298/files/ba84216994ae6bcd34ba1a9df8fdd3b28385bd45#diff-8cd7afb316ff774a441fdc76389ece1da5c4f9f79c7a16b42df2a18408e59eaaR54

The above line is a bug fix I spotted while working on it.

2021-07-14 02:31 UTC, calvinaco commented on lib/src/transaction/ow.types.ts
> +    signerAccounts: ow.optional.array.ofType(owSignerAccount()),
I think we have made `SignableTransaction` no longer compatible with previous version. I am thinking if we should introduce a V2 to it as well.

2021-07-14 03:48 UTC, cdc-Hitesh commented on lib/src/transaction/ow.types.ts
> +    signerAccounts: ow.optional.array.ofType(owSignerAccount()),
@calvinaco  I agree, even @eddycpc  pointed this thing out in this comment https://github.com/crypto-org-chain/chain-jslib/pull/298#discussion_r668797804 

I will introduce it under V2 then.

2021-07-14 07:34 UTC, eddycpc commented on lib/src/cosmos/v1beta1/types/tx.ts
> +        amount?: ICoin[];
As long as it works perfectly with the older API, it should be all good

2021-07-14 07:40 UTC, eddycpc commented on lib/src/coin/coin.spec.ts
> +    xdescribe('add', function () {
I think if a test like this is not passing, then very likely there was a breaking change along the way.

2021-07-14 08:08 UTC, eddycpc commented on lib/src/transaction/msg/gov/MsgSubmitProposal.ts
> +            }
@cdc-Hitesh there seems to be a number of warning related to new code paths not covered by new unit tests

2021-07-14 12:41 UTC, cdc-Hitesh commented on lib/src/coin/coin.spec.ts
> +    xdescribe('add', function () {
Exactly. 
I am wondering how to resolve this issue.

Shall we roll out CoinV2 as well?

2021-07-14 19:40 UTC, eddycpc commented on lib/src/coin/coin.spec.ts
> +    xdescribe('add', function () {
> Shall we roll out CoinV2 as well?

Let's do this I think it's of best interest we don't modify largely the initial coin implementation which has worked pretty well thus far.

2021-07-15 20:54 UTC, eddycpc requested changes

2021-07-15 20:54 UTC, eddycpc commented on lib/src/transaction/types.ts
> +    LEGACY_AMINO_JSON = 127,
Why is `LEGACY_AMINO_JSON` changing? Wonder if this won't impact our usage of Ledger signing 🤔 .

2021-07-16 04:55 UTC, cdc-Hitesh commented on lib/src/transaction/types.ts
> +    LEGACY_AMINO_JSON = 127,
The usage of `LEGACY_AMINO_JSON` in our code base is used as more of a `conditional` than of a `final value`.
This should have appropriate behaviour.

We can deep dive together if you want @eddycpc

2021-07-16 06:50 UTC, eddycpc submitted a review, later dismissed
Looking good for me now

2021-07-19 05:42 UTC, calvinaco commented on README.md
> +Machine 1(Online):
```suggestion
Machine 1 (Online):
```

2021-07-19 05:44 UTC, calvinaco commented on README.md
> +            });
```suggestion
const signableTx = new SignableTransaction({
    rawTxJSON: exportUnsignedCosmosJSON,
    network: <CroNetwork>,
     signerAccounts: signerAccountsOptional,
});
```

2021-07-19 05:45 UTC, calvinaco commented on README.md
> +            const msgSend = cro.v2.bank.MsgSendV2.fromCosmosMsgJSON(msgSendJson, CroNetwork.Testnet);
```suggestion
const msgSend = cro.v2.bank.MsgSendV2.fromCosmosMsgJSON(msgSendJson, CroNetwork.Testnet);
```

2021-07-19 05:45 UTC, calvinaco commented on README.md
> +            const msgFundCommPool = cro.v2.distribution.MsgFundCommunityPoolV2.fromCosmosMsgJSON(msgFundCommunityPoolJson, CroNetwork.Testnet);
```suggestion
const msgFundCommPool = cro.v2.distribution.MsgFundCommunityPoolV2.fromCosmosMsgJSON(msgFundCommunityPoolJson, CroNetwork.Testnet);
```

2021-07-19 05:46 UTC, calvinaco commented on README.md
> +        });
```suggestion
const msgSendV2 = new cro.v2.bank.MsgSendV2({
    fromAddress: 'tcro165tzcrh2yl83g8qeqxueg2g5gzgu57y3fe3kc3',
    toAddress: 'tcro184lta2lsyu47vwyp2e8zmtca3k5yq85p6c4vp3',
     amount: [coin1, coin2],
});
```

2021-07-19 06:22 UTC, cdc-Hitesh commented on README.md
> +            });
Thanks.

2021-07-19 06:58 UTC, calvinaco commented on lib/src/coin/v2.coin/v2.coin.ts
> +            if (baseAmount.gt(CoinV2.TOTAL_SUPPLY_STRING)) {
Do we need this check for base amount? If I didn't mistake this is the non-CRO coin right?

2021-07-19 06:59 UTC, eddycpc commented
Can you change the based branch, since `tx-revamp-dev` has now been merged to dev?

2021-07-19 07:01 UTC, calvinaco commented on lib/src/coin/v2.coin/v2.coin.ts
> +            if (baseAmount.gt(CoinV2.TOTAL_SUPPLY_STRING)) {
Oh I read the logic again, I think we need to check if it is `basecro` or `basetcro`

2021-07-19 20:21 UTC, cdc-Hitesh commented on lib/src/coin/v2.coin/v2.coin.ts
> +            if (baseAmount.gt(CoinV2.TOTAL_SUPPLY_STRING)) {
Ohh man, This comment was held in `submit review` button to be clicked😭 😭 . Were you able to read this comment earlier in the day? Holy Github.

2021-07-21 18:28 UTC, calvinaco reviewed
Overall is looking good. Please refer to the comment below. I have review majority of it, but still 10 more files to review and will finish them tomorrow.

I think there are a few things I want to point out to be revisited in a separate issue:
1. What should be the function of CoinV2 and how should it handle CRO and non-CRO denoms
2.  `fromCosmosMsgJSON` is accepting a network params, should we use the netwrok from its parent? This may change the signature of it so we may to corporate it in this version to avoid changing signature in the future.
3. In the `fromCosmosMsgJSON`, the structure integrity check relies of `Objec.keys(...).length` which is not reliable. It should use `ow` to check it. But this can be done in separate issue.

2021-07-21 18:28 UTC, calvinaco commented on lib/src/transaction/msg/staking/MsgCreateValidator.ts
> +            }
The intention here is not very clear and may fail for example `Object.keys(parsedMsg.value).length === 2)` does not necessarily mean it contains `amount` and `denom`. I think you need to use ow type checking here.

But this could be done in a separate issue and PR.

2021-07-22 06:10 UTC, cdc-Hitesh commented on lib/src/transaction/msg/staking/MsgCreateValidator.ts
> +            }
Noted. 
Opened an issue: https://github.com/crypto-org-chain/chain-jslib/issues/305

2021-07-22 06:15 UTC, cdc-Hitesh commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.ts
> +                upgradedClientState = undefined;
`upgraded_client_state` is an optional field for this message type plus in addition to this we don't have the exact JSON schema of this variable. Hence I kept it by default `undefined` so as to not break the usage.

On throwing, I think we should throw on non-empty values like above

2021-07-22 06:16 UTC, cdc-Hitesh commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.ts
> +                throw new Error('Invalid `height` attribute in Plan.');
`height` is a required field and `time` is an optional field.

2021-07-22 06:32 UTC, cdc-Hitesh commented on lib/src/transaction/msg/bank/msgsend.ts
> +        public static fromCosmosMsgJSON(msgJsonStr: string, network: Network): MsgSend {
- I just wanted it to support any `network`on demand when decoding JSON

Wanted to make sure it's loosely coupled when we want to extend our sdk to any cosmos network in future.

But I agree with the fact that we can use the `config.network` for now.

2021-07-22 06:35 UTC, cdc-Hitesh commented on lib/src/transaction/msg/distribution/MsgFundCommunityPool.ts
> +        public static fromCosmosMsgJSON(msgJsonStr: string, network: Network): MsgFundCommunityPool {
https://github.com/crypto-org-chain/chain-jslib/pull/298#discussion_r674532819

2021-07-22 06:38 UTC, cdc-Hitesh commented on lib/src/coin/v2.coin/v2.coin.ts
> +                }
Noted.Thanks.
https://github.com/crypto-org-chain/chain-jslib/issues/306

2021-07-22 06:45 UTC, cdc-Hitesh commented on lib/src/coin/v2.coin/v2.coin.ts
> +                return this.receivedAmount.toString();
>Correct me if I am wrong.

Yes you are right. `this.receivedAmount` is introduced to handle non-cro amounts.

2021-07-22 06:55 UTC, cdc-Hitesh commented on lib/src/coin/v2.coin/v2.coin.ts
> +                return this.receivedAmount.toString();
> Overall is looking good. Please refer to the comment below. I have review majority of it, but still 10 more files to review and will finish them tomorrow.
> 
> I think there are a few things I want to point out to be revisited in a separate issue:
> 
> 1. What should be the function of CoinV2 and how should it handle CRO and non-CRO denoms
> 2. `fromCosmosMsgJSON` is accepting a network params, should we use the netwrok from its parent? This may change the signature of it so we may to corporate it in this version to avoid changing signature in the future.
> 3. In the `fromCosmosMsgJSON`, the structure integrity check relies of `Objec.keys(...).length` which is not reliable. It should use `ow` to check it. But this can be done in separate issue.

2. I think we can change this now specifically for `fromCosmosMsgJSON` methods. I just wanted to see our message types become network agnostic when we want to support multiple cosmos networks (let's keep it for future then).
3. `Object.key....` check can be taken care of in next iteration, as you said.

1. CoinV2 should basically handle both cro and non-cro coins.
- One approach is to remove the `unit` part from constructor and make the `denom` a required value. This way our SDK becomes dumb and we also remove CRO supply related checks.

@calvinaco

2021-07-23 03:44 UTC, calvinaco commented on lib/src/coin/v2.coin/v2.coin.ts
> +                return this.receivedAmount.toString();
> One approach is to remove the unit part from constructor and make the denom a required value. This way our SDK becomes dumb and we also remove CRO supply related checks.

Yes I think this actually make sense because the `unit` is starting to become confusing. For CRO we could possibly have another helper class to help the conversion instead.

Say
- CoinV3: becomes a deadly simple coin with `amount` and `denom`
- CROCoin: with methods like `fromBaseUnit`, `fromCRO` and `toCoin` as helper

2021-07-23 03:45 UTC, calvinaco commented on lib/src/transaction/msg/bank/msgsend.ts
> +        public static fromCosmosMsgJSON(msgJsonStr: string, network: Network): MsgSend {
My though is like if one want to import a tx from another, they should do `new CroSDK({network})` for each different network and use the message inside the instantiated SDK.

2021-07-23 03:54 UTC, cdc-Hitesh commented on lib/src/coin/v2.coin/v2.coin.ts
> +                return this.receivedAmount.toString();
Agree.
- `CROCoin` sounds like almost a good idea for CRO related
- We can make `CoinV2` act as an equivalent of your `CoinV3` ( I think it's better to avoid introducing Version increments, but I am all ears)

2021-07-23 03:56 UTC, cdc-Hitesh commented on lib/src/transaction/msg/bank/msgsend.ts
> +        public static fromCosmosMsgJSON(msgJsonStr: string, network: Network): MsgSend {
Yes, I agree the current structure allows us to initialise the network in starting.
Thanks.

I have opened another PR #307  for the point above.

2021-08-10 07:07 UTC, cdc-Hitesh commented
@calvinaco @crypto-3dd  
Can we review this pr for the final merge?

2021-08-10 07:25 UTC, calvinaco approved these changes

2021-08-10 09:53 UTC, crypto-3dd approved these changes

2021-08-10 11:44 UTC, merged