Problem: Offline SIgning and TxDecoder Issues | Eslint Fix
crypto-org-chain/chain-jslib pull request #313
Opened 2021-07-26 06:39 UTC by cdc-Hitesh

PR #311

2021-07-27 06:53 UTC, crypto-3dd commented on lib/e2e/tx-decoder/compare.ts
> +            await new Promise((resolve) => setTimeout(resolve, 60000));
I'm somehow curious why wait for a whole minute, is there a reason behind that long wait time?

2021-07-27 06:56 UTC, crypto-3dd commented on lib/src/transaction/amino.spec.ts
> +            .setFees([cro.v2.CoinV2.fromBaseUnit('10000')])
Was the old `setFee` removed? Does this impact the way we did previously transactions, I'm curious if backwards compatibility is preserved here.

2021-07-27 07:03 UTC, cdc-Hitesh commented on lib/e2e/tx-decoder/compare.ts
> +            await new Promise((resolve) => setTimeout(resolve, 60000));
I am not sure but I think to avoid over-requesting the RPC server and letting the server re-settle up a few things.

Calvin can answer this precisely.

2021-07-27 07:06 UTC, cdc-Hitesh commented on lib/src/transaction/amino.spec.ts
> +            .setFees([cro.v2.CoinV2.fromBaseUnit('10000')])
This test case is a `v2` checker.
And yes `setFee` is marked deprecated in V2 RawTransaction.

The original `RawTransaction` still has the `setFee` function and here backwards compatibility is taken care off.

Still let me know your thought.

2021-07-27 07:20 UTC, calvinaco requested changes

2021-07-27 07:20 UTC, calvinaco commented on lib/src/transaction/v2.raw.ts
> +         * Set fee to the raw tx
```suggestion
         * Sets a `single` only fee amount to the raw tx
```

2021-07-27 07:20 UTC, calvinaco commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts
> +            expect(SoftwareUpgradeProposal.plan.upgradedClientState).to.be.undefined;
Here should it throw instead of silently swallowing the `upgradedClientState`?

2021-07-27 07:22 UTC, calvinaco commented on lib/e2e/tx-decoder/compare.ts
> +            await new Promise((resolve) => setTimeout(resolve, 60000));
This retry is to handle the rate limit case and could be shorten, on our public RPC the rate limit is per n-minutes interval.

2021-07-27 07:25 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +                clonedDecodedParams.commission[key] = rateToBig.div(new Big(1e18)).toFixed(18);
Noted.
Better to be safe.

2021-07-27 07:25 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +                clonedDecodedParams.commissionRate = rateToBig.div(new Big(1e18)).toFixed(18);
Noted.

2021-07-27 08:13 UTC, cdc-Hitesh commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts
> +            expect(SoftwareUpgradeProposal.plan.upgradedClientState).to.be.undefined;
Actually `.plan.upgradedClientState` is an optional parameter, hence had to suppress the tslint error.

2021-07-27 14:33 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +                clonedDecodedParams.commission[key] = rateToBig.div(new Big(1e18)).toFixed(18);
Resolved.

2021-07-27 14:34 UTC, cdc-Hitesh commented on lib/src/utils/txDecoder.ts
> +                clonedDecodedParams.commissionRate = rateToBig.div(new Big(1e18)).toFixed(18);
Resolved

2021-07-29 17:15 UTC, calvinaco commented on lib/src/transaction/v2.raw.ts
> +         * @returns {RawTransaction}
```suggestion
         * @returns {RawTransactionV2}
```

2021-07-29 17:16 UTC, calvinaco approved these changes

2021-07-29 17:17 UTC, calvinaco commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts
> +            expect(SoftwareUpgradeProposal.plan.upgradedClientState).to.be.undefined;
Sorry I mean in the original JSON there's
```
"upgradedClientState": { "typeUrl": "someTypeUrl", "value": "someValue"}
```

But in the parsed version you expect it to be undefined.

2021-07-30 08:17 UTC, crypto-3dd approved these changes
LGTM

2021-08-02 10:05 UTC, cdc-Hitesh commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts
> +            expect(SoftwareUpgradeProposal.plan.upgradedClientState).to.be.undefined;
As discussed keeping the TODO. I will add a throw statement here.

2021-08-02 10:44 UTC, calvinaco commented on lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts
> +        it('should set `upgradedClientState` as undefined when non-empty', function () {
```suggestion
        it('should throw when `upgradedClientState` is non-empty', function () {
```

2021-08-02 10:45 UTC, calvinaco approved these changes

2021-08-02 10:52 UTC, merged