Problem: add IBC Amino transaction support
crypto-org-chain/chain-jslib pull request #336
Opened 2021-09-13 09:04 UTC by cdc-Hitesh

- Added IBC Amino support

Fixes #335

2021-09-13 11:09 UTC, crypto-3dd requested changes

2021-09-13 11:09 UTC, crypto-3dd commented on lib/src/transaction/msg/ibc/applications/MsgTransfer.ts
> +            this.timeoutTimestampInNanoSeconds = options.timeoutTimestamp;
I think we should have only changed `options.timeoutTimestamp` to `options.timeoutTimestampInNanoSeconds ` because it's the user-facing property/field.

Internally it can stay `timeoutTimestamp`, but on the caller/user side we can then use the `timeoutTimestampInNanoSeconds` notation to add more precision

2021-09-13 14:13 UTC, cdc-Hitesh commented on lib/src/transaction/msg/ibc/applications/MsgTransfer.ts
> +            this.timeoutTimestampInNanoSeconds = options.timeoutTimestamp;
@crypto-3dd 

Actually, this is the user value only. 

The actual key still remains `timeoutTimestamp` if you see the `.toRawMsg()` function.

2021-09-13 15:16 UTC, crypto-3dd requested changes

2021-09-13 15:16 UTC, crypto-3dd commented on lib/src/transaction/msg/ibc/applications/MsgTransfer.ts
> +            this.timeoutTimestampInNanoSeconds = options.timeoutTimestamp;
@cdc-Hitesh by user-facing I mean when the user passes the value to the property. It still `options.timeoutTimestamp` which is still a very confusing property without specifying that it expects the value in nano seconds.

We need to move from this
        
```
const MsgTransfer = new cro.ibc.MsgTransfer({
            .....
            timeoutTimestamp: Long.fromString('1620640362229420996'),
        });
```

to this

```
        
const MsgTransfer = new cro.ibc.MsgTransfer({
            .....
            timeoutTimestampInNanoSeconds: Long.fromString('1620640362229420996'),
        });
```
The internal implementation doesn't need changing per se. Only the user facing part.

2021-09-13 17:28 UTC, crypto-3dd commented
The property name hasn't been updated over here.

2021-09-14 07:18 UTC, crypto-3dd approved these changes

2021-09-14 07:18 UTC, merged