Problem: Support EVM to Bech32 address
crypto-org-chain/chain-jslib pull request #341
Opened 2021-09-13 14:07 UTC by cdc-Hitesh

Fixes #337

2021-09-13 15:20 UTC, crypto-3dd requested changes

2021-09-13 15:20 UTC, crypto-3dd commented on lib/src/transaction/msg/ibc/applications/MsgTransfer.spec.ts
> +            timeoutTimestamp: Long.fromString('1620640362229420996'),
```suggestion
            timeoutTimestampInNanoSeconds: Long.fromString('1620640362229420996'),
```

This is the confusing part I wanted to highlight, we would need to specify it expected in nanoseconds, that's because traditionally timestamp is usually in milli seconds.

2021-09-13 15:23 UTC, crypto-3dd requested changes

2021-09-13 15:23 UTC, crypto-3dd commented on lib/src/utils/address.ts
> +export const getBech32AddressFromEVMAddress = (evmAddress: string, bech32Prefix: string) => {
You might need to export this functionality so that external library users can use it. I haven't seen it yet being exported.

You can export it alongside other utility functions that we are currently exporting.

2021-09-13 15:41 UTC, cdc-Hitesh commented on lib/src/transaction/msg/ibc/applications/MsgTransfer.spec.ts
> +            timeoutTimestamp: Long.fromString('1620640362229420996'),
Yes, I have renamed the user end to signify that it's expected in nano Seconds.

Or do you mean something else?

2021-09-13 15:41 UTC, cdc-Hitesh commented on lib/src/utils/address.ts
> +export const getBech32AddressFromEVMAddress = (evmAddress: string, bech32Prefix: string) => {
True !
Thanks for the input.

2021-09-13 17:29 UTC, crypto-3dd commented on lib/src/utils/index.ts
> +    convertEVMToBech32Address: getBech32AddressFromEVMAddress,
```suggestion
    convertEVMAddressToBech32Address: getBech32AddressFromEVMAddress,
```

2021-09-14 07:21 UTC, crypto-3dd approved these changes

2021-09-14 07:25 UTC, merged